### ISSUE TITLE
Not able to build uppload

### ISSUE THREAD

**Issue by phlegx** [elninotech/uppload#709]
**Describe the bug**
I have followed the contribution description. After installed all required software I run `yarn install` and `yarn build`. But build fails.

**To Reproduce**
1. Install node, yarn, gulp, etc.
2. Execute `yarn install`
3. Execute `yarn build`

**Expected behavior**
A working dev and build environment.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 3.2.1

**Additional context**
The error:

```
$ yarn build
yarn run v1.22.10
$ npm run build-package && node scripts/build-scss.js

> uppload@3.2.1 build-package
> gulp build && npm run build-browser

[16:31:39] Using gulpfile ~/uppload/gulpfile.js
[16:31:39] Starting 'build'...
@rollup/plugin-typescript TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?
@rollup/plugin-typescript TS2774: This condition will always return true since this function is always defined. Did you mean to call it instead?
[16:31:43] 'build' errored after 3.82 s
[16:31:43] Error: @rollup/plugin-typescript: Rollup 'dir' option must be used when Typescript compiler option 'outDir' is specified.
    at error (/home/user/uppload/node_modules/rollup/dist/shared/rollup.js:151:30)
    at throwPluginError (/home/user/uppload/node_modules/rollup/dist/shared/rollup.js:19351:12)
    at Object.error (/home/user/uppload/node_modules/rollup/dist/shared/rollup.js:20001:20)
    at validatePaths (/home/user/uppload/node_modules/@rollup/plugin-typescript/dist/index.js:369:25)
    at Object.renderStart (/home/user/uppload/node_modules/@rollup/plugin-typescript/dist/index.js:658:13)
    at /home/user/uppload/node_modules/rollup/dist/shared/rollup.js:20206:25
    at async Promise.all (index 0)
    at async Bundle.generate (/home/user/uppload/node_modules/rollup/dist/shared/rollup.js:13552:13)
    at async handleGenerateWrite (/home/user/uppload/node_modules/rollup/dist/shared/rollup.js:21022:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by victorlap** [comment]
Hi @phlegx. uppload is tested and should work on node 14 and 16 at this moment
